# Generated by Django 4.1.7 on 2023-02-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=15)),
                ('phno', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Patientreg',
        ),
    ]
